### ISSUE TITLE
Is coloring auto completion output expected behavior?

### ISSUE THREAD

**Issue by ghost** [simnalamburt/shellder#11]
I hit tab:

<img width="857" alt="screen shot 2016-01-27 at 3 52 12 am" src="https://cloud.githubusercontent.com/assets/8317250/12591239/2f8a932a-c4aa-11e5-8b7f-5e576c746a2e.png">

**Comment by simnalamburt** [comment]
Acknowledged, will be fixed

**Comment by bucaran** [comment]
:+1:

**Comment by ghost** [comment]
Hi! Any plans to fix this? :confused:

**Comment by simnalamburt** [comment]
Fixed it. Sorry for the delay!
