### ISSUE TITLE
Strange characters on ubuntu :\

### ISSUE THREAD

**Issue by athanclark** [simnalamburt/shellder#12]
Hi there, I am getting these weird characters instead of the normal block-like characters that should be shown. Is this because I'm using ubuntu and not a mac? Say it ain't so :(

![sadface](https://cloud.githubusercontent.com/assets/1534966/12837281/3effe78a-cb7e-11e5-9045-882589f519b2.png)

**Comment by simnalamburt** [comment]
It's because of the fonts. You need a powerline patched font to use `shellder`.

There're many powerline patched fonts and personally I like [monaco for powerline](https://gist.github.com/baopham/1838072)

#### TODO
- [ ] Mention powerline patched fonts on README.md

**Comment by metal3d** [comment]
I use this:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts 
Get one of the fonts (complete, not "windows", for example: https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20for%20Powerline%20Nerd%20Font%20Complete%20Mono.otf) then click on the font, press "install" button and use it in your terminal configuration.
