### ISSUE TITLE
warning: function available is deprecated and will be removed soon.

### ISSUE THREAD

**Issue by Alxandr** [simnalamburt/shellder#29]
I just updated my `omf` modules, and the result is a lot of `warning: function available is deprecated and will be removed soon.` for each command I type. Funnily enough, the issue goes away if I copy the block:

```fish
if printf '%s\n' '2.2.0' $FISH_VERSION | sort --check=silent --version-sort
  # Current version ≥ 2.2.0
  function available -a name -d "Check if a function or program is available."
    command -v "$name" ^/dev/null >&2
  end
else
  # Current version < 2.2.0
  function available -a name -d "Check if a function or program is available."
    type "$name" ^/dev/null >&2
  end
end
```

and run it in my shell.

![image](https://user-images.githubusercontent.com/112334/34296309-5b117216-e712-11e7-9667-5a0420b7d8dd.png)

**Comment by simnalamburt** [comment]
Thanks you for reporting the long lived issue, and enduring my late reply. Actually I was quite surprised to realize that it was an issue that had been happening for quite some time.

Looks like shellder accidentally shares the name of an internal function with oh-my-fish. I'll merge that patch soon and hopefully it will resolve the issue. Happy new year!

###### References
- https://github.com/oh-my-fish/oh-my-fish/issues/428#issuecomment-284968706
- https://github.com/oh-my-fish/oh-my-fish/blob/cc3f836db1cda53433b99dbddc877b518b1a7314/pkg/omf/functions/compat/available.fish#L1
- https://github.com/simnalamburt/shellder/blob/b6753bbc1b185aed043b52cecf1a31dad1d11b73/fish_prompt.fish#L242
