### ISSUE TITLE
Oh My Zsh 종속성 제거

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/shellder#3]
omz 없으면 실행 안되는지 몰랐음.

Thank you @wookayin

**Comment by wookayin** [comment]
일단 이렇게 되는것으로 보임 (?)

```
% zplug load
$(build_prompt)
```

**Comment by wookayin** [comment]
zsh 옵션중에 `setopt prompt_subst` 가 있는데 이걸 활성화해주어야 함 (omz에서는 자동 등록되므로)

**Comment by simnalamburt** [comment]
`parse_git_dirty()` 함수를 복붙하고, 리턴값을 바꿔줘야함
