### ISSUE TITLE
How to enable it??

### ISSUE THREAD

**Issue by isbm** [simnalamburt/shellder#33]
I think I am missing something from the documentation or it is just broken.
I've installed it via `zplug`, then added `zplug 'simnalamburt/shellder', as:theme`. And... nothing chagned. Issuing `zplug ... as:theme` results to:

```
[zplug] simnalamburt/shellder: already managed
```

Uhmm... OK, now what? Would be great to have a bit better `README.md` that allows dumb users like me to just have it without spending hours debigging shell code why this is not working...

**Comment by simnalamburt** [comment]
Sorry it's my fault not to update README. Development of zplug has been discontinued. I strongly suggest avoid using it. Please try https://github.com/zdharma/zinit instead.

```zsh
zinit light simnalamburt/shellder
```

I'll update README

**Comment by isbm** [comment]
@simnalamburt fork you! :wink:
