### ISSUE TITLE
Async git status

### ISSUE THREAD

**Issue by lazywei** [simnalamburt/shellder#9]
Hi,

I'm wondering if it is possible to make the "displaying git status" asynchronous? If we keep it synchronous, then we have to wait for a moment after every command (because `git status` takes time). This will be critical in a large project.

How do you think?

Thanks

**Comment by simnalamburt** [comment]
If that's possible, it will be great solution but I have no idea how to implement that. Currently I'm planning to skip `git status` if it takes more than 1 second.

**Comment by simnalamburt** [comment]
Looks like https://github.com/sindresorhus/pure does some async git status update. I'll find out how it did it

###### See also
- https://github.com/mafredri/zsh-async

**Comment by simnalamburt** [comment]
https://github.com/romkatv/powerlevel10k did this. Closing
